name: Test __CATALOG_ID__-catalog

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Type-check
        run: pnpm types:check

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
